### ISSUE TITLE
Ubuntu compile error

### ISSUE THREAD

**Issue by p3yot3** [syscoin/syscoin#179]
Using:

./autogen.sh
./configure --disable-tests --without-gui
make

I get this error:

Making all in src
make[1]: Entering directory /home/blah/syscoin-3.0.1/src'
make[2]: Entering directory /home/blah/syscoin-3.0.1/src'
  CXX      syscoind-syscoind.o
  CXX      libsyscoin_server_a-alias.o
In file included from assetallocation.h:14:0,
                 from offer.h:14,
                 from alias.cpp:6:
graph.h:6:43: fatal error: boost/graph/hawick_circuits.hpp: No such file or directory
 #include <boost/graph/hawick_circuits.hpp>
                                           ^
compilation terminated.
make[2]: *** [libsyscoin_server_a-alias.o] Error 1
make[2]: Leaving directory /home/blah/syscoin-3.0.1/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory /home/blah/syscoin-3.0.1/src'
make: *** [all-recursive] Error 1
blah@blah:~/syscoin-3.0.1$

All dependencies are met. I get the same error if I clone from git too.

**Comment by sidhujag** [comment]
what boost version?

**Comment by sidhujag** [comment]
you install boost-graph-dev?

**Comment by p3yot3** [comment]
Boost Version: 1.54.0.1ubuntu1

"apt-get install libboost-graph-dev" gives me:

libboost-graph-dev is already the newest version.

I've not had any issues compiling Syscoin or any other wallets before with the current setup. All updates are installed.

**Comment by sidhujag** [comment]
you need newer boost, graph is not in another other coins including older syscoin. 1.64-1.66 is needed.

**Comment by p3yot3** [comment]
Upgraded to boost 1.66 & everything seemed fine until:

AR       leveldb/libleveldb.a
  CXX      leveldb/port/leveldb_libleveldb_sse42_a-port_posix_sse.o
  AR       leveldb/libleveldb_sse42.a
  CXX      leveldb/helpers/memenv/leveldb_libmemenv_a-memenv.o
  AR       leveldb/libmemenv.a
make[3]: Entering directory /home/blah/syscoin/src/secp256k1'
gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
gcc gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
make[3]: Leaving directory /home/blah/syscoin/src/secp256k1'
  CXXLD    syscoind
libsyscoin_wallet.a(libsyscoin_wallet_a-wallet.o): In function copy_file':
/usr/include/boost/filesystem/operations.hpp:539: undefined reference to boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
libsyscoin_wallet.a(libsyscoin_wallet_a-wallet.o): In function path<boost::filesystem::directory_entry>':
/usr/include/boost/filesystem/path.hpp:144: undefined reference to boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
libsyscoin_wallet.a(libsyscoin_wallet_a-wallet.o): In function `copy_file':
/usr/include/boost/filesystem/operations.hpp:544: undefined reference to boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
libsyscoin_util.a(libsyscoin_util_a-utiltime.o): In function sleep_for':
/usr/include/boost/thread/pthread/thread_data.hpp:258: undefined reference to boost::this_thread::hidden::sleep_for(timespec const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [syscoind] Error 1
make[2]: Leaving directory /home/blah/syscoin/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory /home/blah/syscoin/src'
make: *** [all-recursive] Error 1
blah@blah:~/syscoin$

Damn. Thought I had it there......

**Comment by sidhujag** [comment]
try to make clean and rebuild?

**Comment by p3yot3** [comment]
It was a fresh git clone, same error on the 3.0.1 source code download too......failed twice on each.

**Comment by p3yot3** [comment]
I will try to compile on a different machine running 16.04 later today to see if the problem is specific to 14.04 or across the board.

Maybe in the meantime you can upload some standalone binaries for Ubuntu?

Thanks.

**Comment by sidhujag** [comment]
sure i can from my 14.04 LTS.

**Comment by p3yot3** [comment]
Same error on 16.04 after installing boost 1.66:

  CXXLD    syscoind
libsyscoin_wallet.a(libsyscoin_wallet_a-wallet.o): In function `copy_file':
/usr/include/boost/filesystem/operations.hpp:539: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
libsyscoin_wallet.a(libsyscoin_wallet_a-wallet.o): In function `path<boost::filesystem::directory_entry>':
/usr/include/boost/filesystem/path.hpp:144: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
libsyscoin_wallet.a(libsyscoin_wallet_a-wallet.o): In function `copy_file':
/usr/include/boost/filesystem/operations.hpp:544: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
libsyscoin_util.a(libsyscoin_util_a-utiltime.o): In function `sleep_for':
/usr/include/boost/thread/pthread/thread_data.hpp:258: undefined reference to `boost::this_thread::hidden::sleep_for(timespec const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [syscoind] Error 1
make[2]: Leaving directory `/home/blah/syscoin/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/blah/syscoin/src'
make: *** [all-recursive] Error 1

**Comment by sidhujag** [comment]
hop in slack #help... you seem to be the only one with this issue

**Comment by p3yot3** [comment]
Slack?  Never used it, wouldn't know where to start.

There's no mention of needing to upgrade the standard boost files to 1.66 in the build documentation, so I can't see how anyone is managing to compile this on Ubuntu by following the build documentation provided.

I've never had to update boost manually before to compile wallets, so I followed this how-to:
https://stackoverflow.com/questions/12578499/how-to-install-boost-on-ubuntu#

Everything seems to install fine, but when I then do:

dpkg -s libboost-dev | grep 'Version'

it still shows the older version, so I presume the older boost isn't getting updated & the newer version is being installed in the wrong place? Where should the location be?

Thanks.

**Comment by willyko** [comment]
Regarding your config not being able to find Boost::Filesystem
try this
./configure --with-boost-libdir=/usr/lib/x86_64-linux-gnu


https://github.com/bitcoin/bitcoin/issues/3219

**Comment by skironDotNet** [comment]
try to build in folder "syscoin" I had also an issue  when building in let say "syscoin-3.0" maybe some paths are hardcoded. Also all commands except autogen must be as sudo, without sudo it complains about one package that is indeed installed

**Comment by alexander-gabriel** [comment]
They must most not use sudo. Seems like you have a permission problem on some dependencies. Those should be readable by all.

**Comment by doublesharp** [comment]
I am able to build in arbitrary directories on Ubuntu 14 with the following script:

```
# syscoin branch
SYSCOIN_BRANCH=master
 
# update libraries
sudo apt-get update
sudo apt-get upgrade -y
 
# build tools
sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils
 
# boost
sudo apt-get install -y libboost-all-dev
 
# bdb 4.8
sudo add-apt-repository -y ppa:bitcoin/bitcoin
sudo apt-get update -y
sudo apt-get install -y libdb4.8-dev libdb4.8++-dev

# zmq
sudo apt-get install -y libzmq3-dev
 
# syscoin source
git clone https://github.com/syscoin/syscoin.git
cd syscoin && git checkout $SYSCOIN_BRANCH
 
# build syscoind and syscoin-cli using available cores
./autogen.sh
./configure --disable-tests --disable-gui-tests --disable-bench
make -j$(nproc) -pipe
 
# install the binaries
sudo make install

**Comment by p3yot3** [comment]
Which boost version are you using?

**Comment by doublesharp** [comment]
```
dpkg -s libboost-dev | grep 'Version'
Version: 1.58.0.1ubuntu1
```

**Comment by p3yot3** [comment]
That's what I started with, but it wouldn't compile.

@sidhujag said above that v1.64-v1.66 was required, so I'm not sure how you managed that.

Are you using 64bit?

**Comment by doublesharp** [comment]
These are running on AWS EC2 and are Ubuntu 16.04 64-bit. I have it at 2 cores right now for compiling but it works with 1 core as well with the script I posted above starting from a base image.

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

```
lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
Stepping:              2
CPU MHz:               2400.092
BogoMIPS:              4800.18
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0,1
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single retpoline kaiser fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt
```

**Comment by p3yot3** [comment]
@sidhujag Please clarify on your statement above regarding exactly what dependencies are needed & what boost version is used/required. I've built & run multiple wallets on my Ubuntu systems, SYS v3 is the only wallet that won't compile.
Pre-built binaries would be a great help in the meantime.

**Comment by skironDotNet** [comment]
I don't have a problem building it on ubuntu 16.04 (xubuntu if that matters) I know libzmq-dev is needed as last dependency,

**Comment by p3yot3** [comment]
Do you mean libzmq3-dev? It's listed as optional in the build.unix doc so shouldn't be needed to compile. I'll install it anyway & give it a try.....

@sidhujag Please clarify on your statement above regarding exactly what dependencies are needed & what boost version is used/required.

**Comment by sidhujag** [comment]
seems I misspoke: Boost-graph is available since 1.55 (with hawick circuit detection algo) https://www.boost.org/doc/libs/1_55_0/libs/graph/doc/index.html

and I have 1.55 installed on 14.04LTS and builds fine:

cat /usr/include/boost/version.hpp | grep "BOOST_LIB_VERSION"
//  BOOST_LIB_VERSION must be defined to be the same as BOOST_VERSION
#define BOOST_LIB_VERSION "1_55"

**Comment by p3yot3** [comment]
@sidhujag Thank you. So my error is not due to boost & I don't have to upgrade it then.

What about libzmq3-dev - is is required as  @skironDotNet states or is it optional as documented?

I'm still unable to compile on 16.04 or 14.04, same errors as above btw.

Edit: Just noticed the new release - will try it now.

Edit2:  Same error.

  CXXLD    syscoind
libsyscoin_wallet.a(libsyscoin_wallet_a-wallet.o): In function `copy_file':
/usr/include/boost/filesystem/operations.hpp:539: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
libsyscoin_wallet.a(libsyscoin_wallet_a-wallet.o): In function `path<boost::filesystem::directory_entry>':
/usr/include/boost/filesystem/path.hpp:144: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
libsyscoin_wallet.a(libsyscoin_wallet_a-wallet.o): In function `copy_file':
/usr/include/boost/filesystem/operations.hpp:544: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
libsyscoin_util.a(libsyscoin_util_a-utiltime.o): In function `sleep_for':
/usr/include/boost/thread/pthread/thread_data.hpp:258: undefined reference to `boost::this_thread::hidden::sleep_for(timespec const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [syscoind] Error 1

This is on 16.04 with libzmq3-dev installed.

**Comment by sidhujag** [comment]
zmq is optional. try with boost 1.55 I do know some version dont work.

**Comment by sidhujag** [comment]
try what this guy did.. 

https://bitcointalk.org/index.php?topic=1466445.2920;topicseen

**Comment by p3yot3** [comment]
> try what this guy did..

https://bitcointalk.org/index.php?topic=1466445.2920;topicseen

YES!!  That worked great. Thanks for the link - someone buy that woman some flowers. I can now upgrade my wallets at last.

**Comment by doublesharp** [comment]
FWIW I just had this same issue on CentOS and was able to fix it by building an updated version of Boost.

```
curl -sL https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.gz -o boost_1_65_1.tar.gz
tar -xvf boost_1_65_1.tar.gz && cd boost_1_65_1
./bootstrap.sh
sudo ./b2 install --with=all toolset=gcc link=static runtime-link=static
sudo ldconfig
LD_LIBRARY_PATH=/usr/local/lib
export LD_LIBRARY_PATH
```

```
./autogen.sh
./configure --with-boost-libdir="$LD_LIBRARY_PATH"
make
```
